### ISSUE TITLE
[meta] TRIC-DT /TEA-DH Integration and Feature Planning

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#159]
**This issue is to keep track of and discuss the integration of the TEA-DH project into the TRIC-DT Innovation and Impact Hub, by focusing on feature development that will provide value for both projects.**

**The items discussed in this issue will be converted into separate issues and tracked using the [projects](https://github.com/alan-turing-institute/AssurancePlatform/projects) roadmap section of this repository.**

## Meta issues

- [ ] Separate out documentation from the GitHub repository? Alternatively build documentation into the React site?
- [x] #397 
- [ ] Switch over to Next.js API
- [x] #413
- [x] #398
- [x] #190

### Assurance Case Repository

A repository for assurance cases (and case studies more generally) to allow users to share and collaborate with others. Possible tasks include:

- [x] #169
- [x] #173
- [x] Community management practices and guidelines
    - [X] Add a [`CONTRIBUTING.md`](https://github.com/alan-turing-institute/AssurancePlatform/blob/main/CONTRIBUTING.md) file
    - [X] Create a [public-facing Slack channel in the Turing Slack](https://join.slack.com/share/enQtNjE1NDMzOTI3MDY2MS1jYTIzNmVhN2RmZTEwNzc5OGJhZWZjOTY1NjJkZDI0Yzc1ZWNjODQ1ODI2NjNhNjJjMGQyYjFhNTY0NWM4OGZk)

 ### UI/UX Improvements

Improve the usability and accessibility of the platform. Possible tasks include:

- [x] #170
- [x] #295
- [x] #363
- [x] #408
- [x] #297
- [x] #299
- [x] #333 
- [x] #334
- [x] #337
- [x] #338
- [x] #405
- [x] #407
- [x] #384
- [x] #296 
- [x] #168
- [x] #174
- [x] #179
- [x] #183
    - [x] Consider how these constraints could feed into interface improvements (e.g. only displaying title and short description).

### Consistency with assurance standards

- [x] #175
- [x] Research into how to make methodology and platform more integrated with current standards (e.g. native support for referencing ISO standards). (#176, see also below)
    - [x] Ensure there's long-term consistency with assurance standards
- [x] #289 (i.e. not just blank box, but maybe DOI, URI, or URL type)
- Front-end
    - [x] #316

### Backend Improvements

- [x] #412
    - [x] #176
- [x] #213 
- [x] #328
- [x] #311
- [x] #181
- [x] #178
- [x] #290

### Collaboration Features

- [ ] Epic: Enable sharing, collaboration, and discussion features
    - [x] #177
    - [x] #189
    - [ ] #440
    - [x] #433
    - [x] #326
- [ ] Develop Groups functionality
    - [x] #325
    - [x] #329

### Authentication

- [ ] Implement NextAuth

### FAIR Auditing

- [x] #235
- [x] #180
  - [x] For example: Is the case schema interoperable? Does the repository enable findability? How is it queryable?

### Skills and Training

- [ ] #182
- [x] #332
- [ ] Construct a course on Trustworthy and Ethical Assurance
- [ ] Embed skills and training into TTW and Turing Commons
  - [ ] Integration into open and reproducible data science (e.g. project governance tool for PIs and PhD students, project teams)
  - [ ] Operationalisation of ethical principles into core attributes and practical decisions (using extensible project lifecycle as a checklist)
  - [ ] Building trust through stakeholder and public engagement (e.g. non-technical versions of public assurance cases)
- [ ] Wider skills and training for standards community and practitioners

### Marketing

- [x] #220
- [x] #398

### Feedback

- [x] #406

**Comment by cassgvp** [comment]
Lots of wonderful ideas on here. Let's also make sure opportunities for community engagement and contributions are signposted.

**Comment by AoifeHughes** [comment]
Is adding something to enable nested / associated diagrams useful and that could allow "modules" as shown in the GSN standard?

@chrisdburr, happy to investigate and prototype if so

**Comment by AoifeHughes** [comment]
- [ ] Can we define a "trusted" / "official" repo for importing these arguments, and also allow users to add their own or custom ones. e.g., we just define how a repo on GitHub is laid out, and then the platform can accept links to import from

**Comment by kallewesterling** [comment]
> Let's also make sure opportunities for community engagement and contributions are signposted.

@cassgvp Would you be able to add a few bullet points for guidance under the "Community management practices and guidelines"? That would make it so much easier for me to manage the last few weeks on this project before the end of the year, when we're sprinting to get things done.

**Comment by chrisdburr** [comment]
> Is adding something to enable nested / associated diagrams useful and that could allow "modules" as shown in the GSN standard?
> 
> @chrisdburr, happy to investigate and prototype if so

In general, "yes". I'd like to find a way to ensure compatibility with GSN more broadly though. So, I'm cautious about rushing this and creating some awkward path dependancy that we have to resolve later down the line.

**Comment by chrisdburr** [comment]
Stale. Closing.
