### ISSUE TITLE
[meta] Plan user guidance and documentation

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#190]
This issue will be used to track the progress of our project page's documentation. 

## Todos

- [x] Setup module tracker page
- [ ] Link HackMD to GH directory for asynchronous co-working
- [ ] Add individual issues to projects tracker
- [ ] Organise documentation sprint

## Links

- HackMD Documentation Tracker: https://hackmd.io/@tea-platform/B1GsUAGep

**Comment by chrisdburr** [comment]
I've setup a new `documentation` branch for us to start drafting these sections, once we've agreed on the scope and structure: https://github.com/alan-turing-institute/AssurancePlatform/tree/documentation/site/docs/guidance

**Comment by kallewesterling** [comment]
I can try to set aside some time to work on setting up a structure and start drafting a bunch of these things, but considering the mention above of "agreeing on the scope and structure", perhaps let's hold off until after Thursday's check-in with you @chrisdburr, @AoifeHughes and I?

**Comment by chrisdburr** [comment]
That's fine. It's a longer piece of work, and something to discuss with @S-Laher as well.

**Comment by kallewesterling** [comment]
Do we also want to ensure that we scope some documentation for contributing to the codebase as well, as we're launching this as an open-source project?

**Comment by chrisdburr** [comment]
> Do we also want to ensure that we scope some documentation for contributing to the codebase as well, as we're launching this as an open-source project?

Yes. Please could you and @AoifeHughes suggest some pages/topics that should be included? And, maybe @cassgvp can add suggestions from a CM perspective (e.g. improvements to code of conduct, PR templates).

**Comment by cassgvp** [comment]
👆🏻  Great idea. Please ping me when you want to discuss/co-work on this.

**Comment by chrisdburr** [comment]
I have created a separate document to track the project page's documentation, including user guidance modules (e.g. general skills and capability building), case studies, and platform documentation (e.g. API documentation, deployment instructions): https://hackmd.io/@tea-platform/B1GsUAGep

I think we should plan for a documentation sprint at some point in November/December @kallewesterling

**Comment by kallewesterling** [comment]
@chrisdburr I wanted to pick up on this issue, where you mention that you want a documentation sprint in Nov/Dec. Since we're over half the November down already, what're your feelings around this? Was there anything in particular that you had in mind for the documentation?

**Comment by chrisdburr** [comment]
Couple of things here:

1. Some of the documentation will need to wait until after the work with Fruto, as user guidance will need to reflect the latest version of the UI (e.g. screenshots). 
2. I think we should still try to find time in one sprint before the end of the year to review and focus on outstanding documentation. There is still work we could do that doesn't depend on the redesign.

**Comment by chrisdburr** [comment]
Closing. Will reopen with updated structure and documentation when new requirements have been established.
