### ISSUE TITLE
[epic] Ensure platform is ready for submission to digital public goods alliance

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#204]
- [ ] Carry out a review of the platform, identify whether all [DPGA's standard indicators](https://digitalpublicgoods.net/standard/) can be met, and make revisions as necessary.
- [ ] Check that we have all the information available for applying to be recognised as a digital public good:
    - [ ] Digital solutions must demonstrate **relevance to one or more SDGs** (Sustainable Development Goals). _Evidence required_:  A description that links the digital solution to the [SDG targets](https://sdg-tracker.org/) detailed under each SDG. This will be required for each SDG that the solution may cater to.
    - [ ] Digital solutions must use an approved **open license**. _Evidence required_: A public link that explicitly mentions an approved open license. Refer here for the [list of approved open licenses](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/licenses.md) accepted.
    - [ ] The **organisation owning the digital solution must be clearly defined**. _Evidence required_: Link(s) to the copyright, trademarks, or publicly available ownership documentation for the digital solutions. It could be a webpage that clearly defines who owns the digital solution. Terms of Service may also indicate the ownership of the digital solutions. Additional legal documentation that provides supporting information will strengthen your application. Digital solutions owned by a parent organisation, could highlight the digital solutions on their website to strengthen the application.
    - [ ] Digital solutions must **not be locked into a specific vendor or product** creating a dependency in order to operate. If there are any mandatory dependencies that create more restrictions than the original license should have an open alternative. Non-mandatory dependencies may be replaced with open alternatives without making significant changes to the core digital solution (the source code). _Evidence required_: Applicants must provide a description of how open-source components are independent and/or list the open alternatives for any closed component(s). Applications should be able to demonstrate that close components can be replaced with open alternatives with minimal configuration changes and without requiring a major overhaul of the entire system. This requirement can be best answered by a technical member of your team.
    - [ ] Digital solutions must have **strong documentation**. The documentation should allow a technical person unfamiliar with the solution to launch and run the digital solution themselves. _Evidence required_: A detailed description of how the solution is documented as well as link(s) to all relevant documents. For software solutions, documentation could include an open repo, technical specifications, functional requirements, etc. For data sets or solutions, documentation could describe all the fields in the set, and provide context on how the data was collected and how it should be interpreted. For content, documentation could include relevant compatible apps, software, hardware required to access the content and any instructions on how to use it. For more details on documentation best practices, please visit [this link](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/documentation.md).
    - [ ] Digital solutions must have **mechanisms for extracting or importing non-PII** (non Personally Identifiable Information) data from or into the system in a non-proprietary format if non-PII data is collected or used. _Evidence required_: A detailed description of how the non-PII data can be imported or exported into non-proprietary formats such as CSV/XML/JSON etc or via exposing the non-PII data through APIs.
    - [ ] Digital solutions must **comply with relevant privacy, domestic and other applicable international laws**. _Evidence required_: If the digital solution collects PII data, then link(s) to the privacy policy, terms of service or other relevant legal documentation must be provided. To strengthen the application, applicants are encouraged to provide a list of the relevant laws that the digital solutions complies within the relevant jurisdiction such as (but not restricted to) General Data Protection Regulation (GDPR), Indian IT Act, Persons with Disabilities Act 2020, Canadian Disabilities Act, Americans with Disabilities Act of 1990, etc.
    - [ ] Digital solutions must **comply with relevant standards, best practices and/or principles**. _Evidence required_: A list of the open standards, best practices & principles that the digital solution adheres to with any relevant links wherever possible. Here is a list of [open standards](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/open-standards.md) and [best practices](https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/best-practices.md) that you may find helpful.
    - [ ] Digital solutions must ensure that steps are taken to **anticipate, prevent and do no harm**. _Evidence required_: (a) If the digital solution collects, stores or distributes PII data, then a list of the types of data that is collected, stored or distributed is required along with a detailed description of the steps taken to prevent adverse impacts resulting from its collection, storage and distribution to ensure the privacy, security and integrity of this data. (b) If the digital solution collects, stores or distributes content, then a detailed description of (1) the policies for identifying inappropriate and illegal content and (2) the processes for detecting, moderating, reporting and removing inappropriate/ illegal content. (c) If the digital solution enables interaction between users, then a detailed description of how the project enables users and contributors to protect themselves from harassment as well as link(s) to relevant policies such as a code of conduct.
- [ ] Submit the assurance platform to the DPGA's registry

## Context
The digital public goods alliance have a registry of open source software. Submitting the assurance platform to this registry would help drive engagement and support another project.

There's a [submission guide](https://digitalpublicgoods.net/submission-guide/) available which has been broken down into individual checkboxes in the list above.

All digital solutions will be reviewed by the Digital Public Goods Alliance’s technical review team to ensure it meets the requirements of each indicator of the DPG Standard. Take this [eligibility test](https://digitalpublicgoods.net/eligibility/) and assess if your digital solution can become a DPG within 5 minutes.

**Comment by kallewesterling** [comment]
Edited the text above to clarify the steps

**Comment by kallewesterling** [comment]
This is left in "Needs more info" and "Won't have" for the time being, as it's pending a lot of work on the UX/UI as well as backend work taking place at the end of Q4 2023.

**Comment by chrisdburr** [comment]
A todo for this issue is 'develop a checklist of requirements' that will allow us to determine when it is ready for submission.

**Comment by kallewesterling** [comment]
> A todo for this issue is 'develop a checklist of requirements' that will allow us to determine when it is ready for submission.

The list in the issue description has been updated.

**Comment by chrisdburr** [comment]
Closing. Stale.
