### ISSUE TITLE
[epic] Implement TourGuide.js

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#332]
Fruto recommended that we implement an option for new users to review a demo assurance case upon account creation. 

We need to plan the scope and content of this assurance case and how the interactive demo will function (e.g. a series of modals that guide the user through the interface). 

- [ ] Plan scope and content of demo case
- [ ] Review technical requirements
- [ ] Create new issue for the implementation of these designs.

**Comment by chrisdburr** [comment]
If anyone knows of any good examples of UI demos that they've come across (e.g. for first time users learning a new interace), please also add links to this issue.

**Comment by gedankenstuecke** [comment]
In the end we didn't use any for AutSPACEs, but @llwelld worked on two alternative options for us, using two different JS "tour" libraries: 

1. Using TourGuideJS: https://github.com/alan-turing-institute/AutSPACEs/pull/575 
2. Using Shepherd.js: https://github.com/alan-turing-institute/AutSPACEs/pull/564 

Both libraries are quite similar in terms of features etc. but in the end we didn't really prioritise either, as based on the community input we felt that it would at best be a short-term fix to usability iirc.

**Comment by chrisdburr** [comment]
Thanks, @gedankenstuecke. Both look like the sort of thing we're after from a cursory glance 🙏 

We'll need to see if either are better suited to React/Material-UI.

**Comment by kallewesterling** [comment]
I think the term we've been looking for is ["Onboarding"](https://uxcam.com/blog/10-apps-with-great-user-onboarding/) in the app.

**Comment by kallewesterling** [comment]
Split this issue into two: (1) Demo case, (2) Implement a tutorial system [this issue]

**Comment by kallewesterling** [comment]
Closed as it has been rewritten as a user story in #425
