### ISSUE TITLE
[meta] Setup releases for repository

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#398]
We should have an option to label different versions of our app on GitHub, which is consistent with our documentation and DockerHub.

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

This will also allow us to setup proper citations for our repository: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by chrisdburr** [comment]
I don't have strong preferences on this, so happy to go with whatever you both deem "best practice" based on existing standards. 

However, I would suggest that in the meantime we update the project README, the documentation, and the homepage to state that the platform is available as a "Research Preview" and that user should expect breaking changes and not store sensitive information anywhere.

**Comment by kallewesterling** [comment]
Sounds good.

- [ ] update the project README: "The platform is available as a 'Research Preview'. You should therefore expect breaking changes and ensure that you do not store any sensitive information anywhere on the system in its current state."
- [ ] update the documentation: "The platform is available as a 'Research Preview'. You should therefore expect breaking changes and ensure that you do not store any sensitive information anywhere on the system in its current state."
- [ ] update the homepage with text: "The platform is available as a 'Research Preview'. You should therefore expect breaking changes and ensure that you do not store any sensitive information anywhere on the system in its current state."

**Comment by chrisdburr** [comment]
Minor amend to all of the above: 

"The Trustworthy and Ethical Assurance platform is currently available as a 'Research Preview'. You should therefore expect breaking changes and ensure that you do not store any sensitive information anywhere on the system in its current state."

Then, perhaps worth directing people to the project board if they're interested in seeing the roadmap. This can just be in the README.

**Comment by cptanalatriste** [comment]
We have adopted [Hash Versioning] for the two artefacts of the platform: the docker images `turingassuranceplatform/eap_backend` and `turingassuranceplatform/eap_frontend`.

Every time we merge into `develop` and `main` branch, we create a new version of each artifact that [is stored in DockerHub](https://hub.docker.com/r/turingassuranceplatform/eap_frontend). At the moment, the latest version of `turingassuranceplatform/eap_frontend`  is [2024-09-17.5b8f31a](https://hub.docker.com/layers/turingassuranceplatform/eap_frontend/2024-09-17.5b8f31a/images/sha256-044e2ee2d0b24855bdd01712f2df995f1e891343308f5d4473465a496af3dd4e?context=explore) and for `eap_backend` is [2024-09-17.540432e](https://hub.docker.com/layers/turingassuranceplatform/eap_backend/2024-09-17.540432e/images/sha256-4b542b776bd6bdd2fbaf25eadf94fd5fc4a8bdacc69c49109ea583c3d0e0d310?context=explore)

**Comment by chrisdburr** [comment]
Great. Thanks for getting this done, @cptanalatriste. Is there anything we need to do now to ensure that new releases are accompanied by something like a changelog? Or does this happen automatically from the commit log?

**Comment by cptanalatriste** [comment]
@chrisdburr at the moment, we do not have a changelog attached to each release. However, It's possible to build it from commit messages (keeping in mind the quality of the messages used so far). I would suggest creating a new issue for implementing a changelog if needed (although I suspect major edits will be required, given that some commit messages are not descriptive enough).

We will also need to, again, think about the audience for these notes: Are they developers, tweaking with TEA code? Are they end-users, only focussed on features? Both?

**Comment by chrisdburr** [comment]
That's fine. Thanks, @cptanalatriste. This isn't a high priority. Just wanted to check. Please could you close this and open a new issue for the changelog steps you've suggested.
